version: '3'
services:
  matomo:
    build: ../mariadb
    volumes:
      - ${MATOMO_HOME}:/usr/src/piwik
      - ../mariadb/piwik.php.ini:/usr/local/etc/php/php.ini
    working_dir: /usr/src/piwik
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    command: php -S matomo:3000
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ../mariadb/data:/var/lib/mysql:delegated
  proxy:
    image: php:7-apache
    volumes:
      - ${MATOMO_TRACKER_PROXY_HOME}:/var/www/html/
    ports:
      - "3001:80"
    links:
      - matomo